import { NextResponse } from 'next/server';
import { GoogleGenerativeAI } from '@google/generative-ai';

const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY);

export async function POST(request) {
  try {
    const { purpose, guidelines, wordCount, category, ageGroup } = await request.json();
    console.log('API: generate-story - Received payload:', { purpose, guidelines, wordCount, category, ageGroup });

    if (!purpose) {
      return NextResponse.json({ error: 'Purpose/topic is required.' }, { status: 400 });
    }

    const model = genAI.getGenerativeModel({ model: "gemini-1.5-flash" });

    const prompt = `Create a children's social story with these specifications:

    **Core Purpose**: 
    ${purpose}
    
    **Story Details**:
    - Target Age: ${ageGroup || '6-8'} years old
    - Category: ${category || 'emotions'}
    - Word Count: Approximately ${wordCount || 200} words
    ${guidelines ? `- Special Guidelines: ${guidelines}` : ''}

    **Writing Instructions**:
    1. Focus on helping children understand and cope with the specific situation
    2. Use simple, clear language appropriate for ${ageGroup || '6-8'} year olds
    3. Keep sentences short (6-10 words on average)
    4. Structure the story into 3-5 clear paragraphs (scenes)
    5. Include positive coping strategies and reassurance
    6. Make the story relatable and comforting
    7. Do NOT include comprehension questions or titles

    **Output Format**:
    - Return ONLY the story text
    - Separate paragraphs/scenes with exactly two newlines (\\n\\n)
    - No scene labels or numbers
    - No additional commentary`;

    const result = await model.generateContent(prompt);
    const response = await result.response;
    const story = response.text();

    if (!story) {
      console.error('No story generated by Gemini');
      return NextResponse.json({ error: 'No story generated' }, { status: 500 });
    }

    return NextResponse.json({ story });
  } catch (error) {
    console.error('Story generation error:', error);
    return NextResponse.json(
      { error: 'Failed to generate story. Please try again.' },
      { status: 500 }
    );
  }
}

/* The above code is for Gemini API. Sometimes, it is unstable. Repace by the following GPT api if that happens */


// import { NextResponse } from 'next/server';
// import OpenAI from 'openai'; 

// // Initialize OpenAI client
// const openai = new OpenAI({
//   apiKey: process.env.GPT_API_KEY,
// });

// export async function POST(request) {
//   try {
//     const { purpose, guidelines, wordCount, category, ageGroup } = await request.json();

//     // Construct the prompt for GPT
//     const systemPrompt = `You are a friendly storyteller AI specialized in creating social stories for children.
//     Your goal is to write positive, encouraging stories that provide clear examples of appropriate behaviors or feelings.
//     Break the story into distinct paragraphs that could easily represent individual scenes.
//     Do NOT include comprehension questions at the end.`;

//     const userPrompt = `Write a children's social story with the following characteristics:
//     - Purpose/Topic: ${purpose}
//     - Main Guidelines: ${guidelines || 'None provided. Be creative and positive.'}
//     - Target Age Group: ${ageGroup || 'General children'}. Adjust language and complexity accordingly.
//     - Category: ${category || 'General'}.
//     - Approximate Length: around ${wordCount || 200} words.`;

//     // Make the API call to OpenAI
//     const completion = await openai.chat.completions.create({
//       model: "gpt-3.5-turbo",
//       messages: [
//         { role: "system", content: systemPrompt },
//         { role: "user", content: userPrompt },
//       ],
//       max_tokens: wordCount ? wordCount * 1.5 : 300, 
//     });

//     const story = completion.choices[0].message.content;

//     if (!story) {
//       return NextResponse.json({ error: 'No story generated' }, { status: 500 });
//     }

//     return NextResponse.json({ story });
//   } catch (error) {
//     console.error('OpenAI API error for text generation:', error);
//     // Provide a more generic error message to the client
//     return NextResponse.json({ error: 'Failed to generate story text. Please try again.' }, { status: 500 });
//   }
// }