import { NextResponse } from 'next/server';
import { GoogleGenerativeAI } from '@google/generative-ai';

const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY);

export async function POST(request) {
  try {
    const { purpose, guidelines, wordCount, category, ageGroup } = await request.json();
    console.log('API: generate-story - Received payload:', { purpose, guidelines, wordCount, category, ageGroup });

    if (!purpose) {
      return NextResponse.json({ error: 'Purpose/topic is required.' }, { status: 400 });
    }

    const model = genAI.getGenerativeModel({ model: "gemini-2.0-flash" });

    const prompt = `Create a children's social story following the official Social Story guidelines by Carol Gray.

Core Purpose: ${purpose}

Story Details:
- Target Age: ${ageGroup || '6-8'} years old
- Category: ${category || 'emotions'}
- Word Count: Approximately ${wordCount || 200} words
{guidelines ? '- Special Guidelines: ${guidelines}' : ''}

Official Social Story Writing Instructions:

1. Use the Sentence Ratio: For every 1 Directive sentence, use 2-5 Descriptive, Perspective, or Affirmative sentences. The story should guide, not command.

2. Incorporate These Sentence Types:
   - Descriptive Sentences: State factual, observable information (e.g., "Sometimes, we go to the grocery store.").
   - Perspective Sentences: Describe the internal states of others (feelings, thoughts, knowledge) to build empathy (e.g., "My mom feels happy when I use my walking feet.").
   - Affirmative Sentences: Reinforce a concept with a shared value or rule (e.g., "This is a safety rule.").
   - Directive Sentences: Gently suggest a positive response or behavior, often phrased as "I will try to..." or "I can...". These must be outnumbered by the other types.

3. Adhere to These Style Rules:
   - Use simple, clear, and reassuring language appropriate for {ageGroup || '6-8'} year olds.
   - Write in the first-person perspective (e.g., "I will try...").
   - Keep sentences short and digestible (6-10 words on average).
   - Structure the narrative into 3-5 clear paragraphs/scenes that logically progress.
   - The overall tone must be patient, positive, and informative.

Output Format:
- Return ONLY the story text, written in the first-person perspective.
- Separate paragraphs/scenes with exactly two newlines (\n\n).
- Do NOT include comprehension questions, titles, or any other commentary.`;

    const result = await model.generateContent(prompt);
    const response = await result.response;
    const story = response.text();

    if (!story) {
      console.error('No story generated by Gemini');
      return NextResponse.json({ error: 'No story generated' }, { status: 500 });
    }

    // Translate to Arabic using the same model
    let storyArabic = '';
    try {
      const translationPrompt = `Translate the following English text to Modern Standard Arabic. Keep it natural and accurate. Return only the Arabic translation without extra commentary or quotes.\n\n"${story}"`;
      const translationResult = await model.generateContent(translationPrompt);
      const translationResponse = await translationResult.response;
      storyArabic = (translationResponse.text() || '').trim().replace(/^(["'`])|(["'`])$/g, '');
    } catch (translationError) {
      console.error('Arabic translation failed:', translationError);
      // Proceed with English story only if translation fails
      storyArabic = '';
    }

    return NextResponse.json({ story, storyArabic });
  } catch (error) {
    console.error('Story generation error:', error);
    return NextResponse.json(
      { error: 'Failed to generate story. Please try again.' },
      { status: 500 }
    );
  }
}

/* The above code is for Gemini API. Sometimes, it is unstable. Repace by the following GPT api if that happens */


// import { NextResponse } from 'next/server';
// import OpenAI from 'openai'; 

// // Initialize OpenAI client
// const openai = new OpenAI({
//   apiKey: process.env.GPT_API_KEY,
// });

// export async function POST(request) {
//   try {
//     const { purpose, guidelines, wordCount, category, ageGroup } = await request.json();

//     // Construct the prompt for GPT
//     const systemPrompt = `You are a friendly storyteller AI specialized in creating social stories for children.
//     Your goal is to write positive, encouraging stories that provide clear examples of appropriate behaviors or feelings.
//     Break the story into distinct paragraphs that could easily represent individual scenes.
//     Do NOT include comprehension questions at the end.`;

//     const userPrompt = `Write a children's social story with the following characteristics:
//     - Purpose/Topic: ${purpose}
//     - Main Guidelines: ${guidelines || 'None provided. Be creative and positive.'}
//     - Target Age Group: ${ageGroup || 'General children'}. Adjust language and complexity accordingly.
//     - Category: ${category || 'General'}.
//     - Approximate Length: around ${wordCount || 200} words.`;

//     // Make the API call to OpenAI
//     const completion = await openai.chat.completions.create({
//       model: "gpt-3.5-turbo",
//       messages: [
//         { role: "system", content: systemPrompt },
//         { role: "user", content: userPrompt },
//       ],
//       max_tokens: wordCount ? wordCount * 1.5 : 300, 
//     });

//     const story = completion.choices[0].message.content;

//     if (!story) {
//       return NextResponse.json({ error: 'No story generated' }, { status: 500 });
//     }

//     return NextResponse.json({ story });
//   } catch (error) {
//     console.error('OpenAI API error for text generation:', error);
//     // Provide a more generic error message to the client
//     return NextResponse.json({ error: 'Failed to generate story text. Please try again.' }, { status: 500 });
//   }
// }